# Generated by Django 5.1.1 on 2024-11-11 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='salesitems',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos_app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ReturnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_returned', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.products')),
            ],
        ),
        migrations.DeleteModel(
            name='sales',
        ),
    ]
