# Generated by Django 5.1.1 on 2024-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_remove_salesitems_sale_id_salesitems_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
