# Generated by Django 5.1.1 on 2024-11-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_product_product_sold_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sold_record',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product_sold_record',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_sold_record',
            name='product_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos_app.products'),
            preserve_default=False,
        ),
    ]
