# Generated by Django 5.1.1 on 2024-11-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_remove_product_sold_record_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_sold_record',
            old_name='code',
            new_name='codes',
        ),
    ]
